version: '3'

services:
  init-ssl:
    image: alpine/openssl
    volumes:
      - ssl-ee:/gitlab
    command: req -x509 -newkey rsa:4096 -keyout /gitlab/${GITLAB_URL:-localhost}.key -out /gitlab/${GITLAB_URL:-localhost}.crt -sha256 -days 365 -nodes -subj "/CN=${GITLAB_URL:-localhost}" -addext "subjectAltName=IP:127.0.0.1,DNS:${GITLAB_URL:-localhost},DNS:${GITLAB_SAN:-foxops-gitlab}"

  init-rb:
    image: alpine
    volumes:
      - config-ee:/etc/gitlab
      - ${PWD}/scripts/gitlab.rb:/src.rb
    command: sh -c 'cat /src.rb | sed -e "s/_GITLAB_URL_/${GITLAB_URL:-localhost}/" -e "s/_GITLAB_PORT_/${GITLAB_PORT:-5443}/" > /etc/gitlab/gitlab.rb'

  gitlab-ee:
    image: gitlab/gitlab-ee:${GITLAB_EE_VERSION:-latest}
    restart: always
    ports:
      - ${GITLAB_PORT:-5443}:${GITLAB_PORT:-5443}
    environment:
      GITLAB_ROOT_PASSWORD: adminadmin
    labels:
      foxops-gitlab/owned: ''
    volumes:
      - config-ee:/etc/gitlab
      - logs-ee:/var/log/gitlab
      - data-ee:/var/opt/gitlab
      - ssl-ee:/etc/gitlab/ssl
      - ${PWD}/scripts/healthcheck-and-setup.sh:/healthcheck-and-setup.sh:Z
    healthcheck:
      test: /healthcheck-and-setup.sh
      interval: 10s
      timeout: 2m
    depends_on:
      init-ssl:
        condition: service_completed_successfully
      init-rb:
        condition: service_completed_successfully

volumes:
  config-ce:
  logs-ce:
  data-ce:
  config-ee:
  logs-ee:
  data-ee:
  ssl-ee: